namespace: hello-az1
resources:
  - hello-az1-serviceexport.yaml
  - hello-az1-multi-serviceexport.yaml
  - hello-az1-svc-ext.yaml
  - hello-az1-svc-ext-multi.yaml
  - ../../base
images:
- name: gcr.io/google-samples/hello-app
  newTag: "1.0"