apiVersion: v1
kind: Service
metadata:
  name: hello
  labels:
    app: hello
    service: hello
  namespace: hello
spec:
  ports:
  - port: 80
    targetPort: 8080
    name: http
  selector:
    app: hello
